trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release

# sdk install
steps:
- task: UseDotNet@2
  displayName: "Install .NET SDK 8.x"
  inputs:
    packageType: sdk
    version: 8.0.x

#nutgen
- script: dotnet restore
  displayName: "Restore packages"

- script: dotnet build --configuration $(buildConfiguration) --no-restore --verbosity minimal
  displayName: "Build solution"

# public
- script: dotnet publish --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)
  displayName: "Publish web app"

- task: PublishBuildArtifacts@1
  displayName: "Publish build artefact"
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: Container 
